cl_chill_person:
    resource: "@CLChillPersonBundle/Resources/config/routing.yml"
    prefix:   /person/

cl_chill_main:
    resource: "@CLChillMainBundle/Resources/config/routing.yml"
    prefix:   /

